import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  primary: [
    {
      type: 'category',
      label: 'Start Here',
      collapsed: false,
      link: { type: 'doc', id: 'start-here/index' },
      items: [
        'start-here/what-is-applied-ai',
      ],
    },
    {
      type: 'category',
      label: 'Disciplines',
      collapsed: false,
      link: { type: 'doc', id: 'disciplines/index' },
      items: [
        { type: 'autogenerated', dirName: 'disciplines' },
      ],
    },
    {
      type: 'category',
      label: 'Playbooks',
      collapsed: false,
      link: { type: 'doc', id: 'playbooks/index' },
      items: [
        { type: 'autogenerated', dirName: 'playbooks' },
      ],
    },
    {
      type: 'category',
      label: 'Foundations',
      collapsed: true,
      link: { type: 'doc', id: 'foundations/index' },
      items: [
        'foundations/signal-theory',
        'foundations/minimum-viable-infrastructure',
        'foundations/teammate-discipline',
      ],
    },
    {
      type: 'category',
      label: 'Engagement Patterns',
      collapsed: true,
      link: { type: 'doc', id: 'engagement-patterns/index' },
      items: [],
    },
    {
      type: 'category',
      label: 'Roles',
      collapsed: true,
      link: { type: 'doc', id: 'roles/index' },
      items: [
        'roles/chief-ai-officer',
        'roles/applied-ai-consultant',
        'roles/ai-enablement-architect',
      ],
    },
    {
      type: 'category',
      label: 'People to Follow',
      collapsed: true,
      link: { type: 'doc', id: 'people-to-follow/index' },
      items: [],
    },
    {
      type: 'category',
      label: 'Onboarding',
      collapsed: true,
      link: { type: 'doc', id: 'onboarding/index' },
      items: [
        'onboarding/curriculum',
        'onboarding/student-journey',
      ],
    },
    {
      type: 'category',
      label: 'Concepts',
      collapsed: true,
      link: { type: 'doc', id: 'concepts/index' },
      items: [
        { type: 'autogenerated', dirName: 'concepts' },
      ],
    },
    {
      type: 'category',
      label: 'Reference',
      collapsed: true,
      link: { type: 'doc', id: 'reference/index' },
      items: [
        {
          type: 'category',
          label: 'Tools',
          link: { type: 'doc', id: 'reference/tools/index' },
          items: [
            { type: 'autogenerated', dirName: 'reference/tools' },
          ],
        },
        {
          type: 'category',
          label: 'Standards',
          link: { type: 'doc', id: 'reference/standards/index' },
          items: [
            'reference/standards/align-md',
            'reference/standards/integrate-md',
          ],
        },
        'reference/voice-rules',
        'reference/glossary',
      ],
    },
  ],
};

export default sidebars;
