import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  primary: [
    {
      type: 'category',
      label: 'Start Here',
      collapsed: false,
      link: { type: 'doc', id: 'start-here/index' },
      items: [
        'start-here/what-is-applied-ai',
      ],
    },
    {
      type: 'category',
      label: 'Disciplines',
      collapsed: false,
      link: { type: 'doc', id: 'disciplines/index' },
      items: [
        { type: 'autogenerated', dirName: 'disciplines' },
      ],
    },
    {
      type: 'category',
      label: 'Playbooks',
      collapsed: false,
      link: { type: 'doc', id: 'playbooks/index' },
      items: [
        { type: 'autogenerated', dirName: 'playbooks' },
      ],
    },
    {
      type: 'category',
      label: 'Foundations',
      collapsed: true,
      link: { type: 'doc', id: 'foundations/index' },
      items: [
        { type: 'autogenerated', dirName: 'foundations' },
      ],
    },
    {
      type: 'category',
      label: 'Perspectives',
      collapsed: true,
      link: { type: 'doc', id: 'perspectives/index' },
      items: [
        { type: 'autogenerated', dirName: 'perspectives' },
      ],
    },
    {
      type: 'category',
      label: 'Engagement Patterns',
      collapsed: true,
      link: { type: 'doc', id: 'engagement-patterns/index' },
      items: [
        { type: 'autogenerated', dirName: 'engagement-patterns' },
      ],
    },
    {
      type: 'category',
      label: 'Roles',
      collapsed: true,
      link: { type: 'doc', id: 'roles/index' },
      items: [
        { type: 'autogenerated', dirName: 'roles' },
      ],
    },
    // TODO: restore People to Follow section once it has real content.
    // {
    //   type: 'category',
    //   label: 'People to Follow',
    //   collapsed: true,
    //   link: { type: 'doc', id: 'people-to-follow/index' },
    //   items: [],
    // },
    {
      type: 'category',
      label: 'Onboarding',
      collapsed: true,
      link: { type: 'doc', id: 'onboarding/index' },
      items: [
        'onboarding/curriculum',
        'onboarding/student-journey',
      ],
    },
    {
      type: 'category',
      label: 'Concepts',
      collapsed: true,
      link: { type: 'doc', id: 'concepts/index' },
      items: [
        { type: 'autogenerated', dirName: 'concepts' },
      ],
    },
    {
      type: 'category',
      label: 'Reference',
      collapsed: true,
      link: { type: 'doc', id: 'reference/index' },
      items: [
        {
          type: 'category',
          label: 'Tools',
          link: { type: 'doc', id: 'reference/tools/index' },
          items: [
            { type: 'autogenerated', dirName: 'reference/tools' },
          ],
        },
        {
          type: 'category',
          label: 'Standards',
          link: { type: 'doc', id: 'reference/standards/index' },
          items: [
            'reference/standards/align-md',
            'reference/standards/integrate-md',
          ],
        },
        'reference/voice-rules',
        'reference/graphic-style',
        'reference/quality-rubric',
        'reference/glossary',
      ],
    },
    'changelog',
  ],
};

export default sidebars;
